# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanowave < Formula
  desc "Autonomous Apple platform app builder"
  homepage "https://github.com/moasq/nanowave"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/moasq/nanowave/releases/download/v0.2.0/nanowave_0.2.0_darwin_all.tar.gz"
  sha256 "895e0334d2a706d00edeeefebd8fd15ddda8560c8f928aad0e0093b848e71df3"

  define_method(:install) do
    bin.install "nanowave"
  end

  test do
    system "#{bin}/nanowave", "--version"
  end
end
