# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanowave < Formula
  desc "Autonomous Apple platform app builder"
  homepage "https://github.com/moasq/nanowave"
  version "0.35.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/moasq/nanowave/releases/download/v0.35.0/nanowave_0.35.0_darwin_all.tar.gz"
  sha256 "a560718ecdead8e0e10445f396d706e0ed1f9ee636b084c4b800ec8cf96bfcb9"

  define_method(:install) do
    bin.install "nanowave"
  end

  test do
    system "#{bin}/nanowave", "--version"
  end
end
